### ISSUE TITLE
How should configuration be changed if docker is not used?

### ISSUE THREAD

**Issue by innomadic** [cagix/pandoc-lecture#2]
I would like to use this tool, but without Docker.  How should I change my Makefiles or other settings if I am not using Docker?  

As it is I get an error like this:

`docker run --rm -v /pathtodemo:/pandoc -v /pathtodemo/../filters:/filters -v /pathtodemo/../resources:/resources debian-texlive pandoc -t beamer --pdf-engine=pdflatex --default-image-extension=pdf -V theme:metropolis -V themeoptions:numbering=none -V themeoptions:progressbar=foot -V fontsize=smaller --slide-level=2 --lua-filter=../filters/tex.lua --include-in-header=../resources/definitions.tex --include-in-header=../resources/beamer.tex --filter pandoc-citeproc -M suppress-bibliography=true -M link-citations=false -f markdown --data-dir=.. --resource-path=.:./figs:.. -o pm_vl01.pdf vl01.md metadata.yaml
make: docker: No such file or directory
make: *** [pm_vl01.pdf] Error 1`

**Comment by magerton** [comment]
I tried replacing https://github.com/cagix/pandoc-lecture/blob/3bc9cb669068fb470c267e3db992d3fbd12a2e4e/demo/Makefile.exams#L15 with the line below, and things seemed to work.

```
PANDOC      ?= pandoc
```

**Comment by hasufell** [comment]
You don't need to replace. `FOO ?= foo` means that `FOO` can be overwritten via environment variable.

**Comment by cagix** [comment]
@innomadic You can either set `PANDOC = pandoc` in the Makefile or set an environment variable, i.e. something like `export PANDOC="/usr/bin/pandoc"` in your `.bashrc` ...
