### ISSUE TITLE
is a multiple choice that is not true/false available?

### ISSUE THREAD

**Issue by innomadic** [cagix/pandoc-lecture#3]
I am unclear on how the multiple choice is to be used.  The documentation says "Each line constitutes a possible answer." (which sounds like multiple choice), but the outputs created a two column choice for each row -- "Correct" and "Incorrect"  -- which makes me think this is designed to create a series of true/false questions.

```
::: {.mc ok="CorrecT" nok="wrOng" points="**je 0.5P** (*Summe 2P*)"}
  [... blablabla.]{.nok}
  [... **wuppie** :)]{.ok}
  [... *fluppie.*]{.nok}
  [... `foobar`.]{.nok}
:::
```

I would like to create a [multiple choice question like these](https://www.overleaf.com/learn/latex/Typesetting%20exams%20in%20LaTeX#Multiple_choice_questions). How is that possible?

**Comment by cagix** [comment]
@innomadic Hmmm, the wording "multiple choice" is a relic from the `exam` class, which still is used in the background to do all the work ... Actually, it is more of a series of true/false answers to the given question. Thus each answer (i.e. each line) is either `true` or `false`.  Currently there is no third option like "I don't know/care/..." ...

**Comment by innomadic** [comment]
Thank you.  So page 42 of the Exam document class PDF
http://www-math.mit.edu/~psh/exam/examdoc.pdf describes the "choices"
environment.  That is not integrated through your pandoc tool is it?

**Comment by cagix** [comment]
not yet, as i wanted to discriminate "*not checked because answer is false*" and "*not checked because i don't really know the answer*" :)

however, it shouldn't be too difficult to implement this in the lua-filter [filters/exams.lua](https://github.com/cagix/pandoc-lecture/blob/master/filters/exams.lua) ... the `exam` environments `oneparchoices` or `checkboxes` could be created from corresponding divs, and the macros `\choice` and `\CorrectChoice` could be translated from corresponding spans, like in the current "mc-questions".

**Comment by cagix** [comment]
@innomadic is this something you would like to see in this project or can we close this issue?

**Comment by innomadic** [comment]
@cagix 

It's certainly a blocker from my using the project as this is a routine sort of question that I use.  

However, I'm afraid I don't have the Latex/Lua skills to take this on at this time, so I won't be able to do it myself.

If it's not a feature you or others are interested in perhaps it should just be closed, and I will continue building my exams in my current less-clever way!

**Comment by cagix** [comment]
ok, i will look into this. unfortunately, i don’t have much spare time at the moment, so please be patient :)

**Comment by cagix** [comment]
@innomadic i created #4 to support the four choices enironments of the `exam` class. could you please review the changes?
